# Generated by Django 5.2.7 on 2025-11-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("can_view", "Can view"),
                    ("can_create", "Can create"),
                    ("can_edit", "Can edit"),
                    ("can_delete", "Can delete"),
                ]
            },
        ),
    ]
