# Generated by Django 5.2.7 on 2025-11-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("librarians", "Librarians"),
                    ("member", "Member"),
                ],
                default="admin",
            ),
        ),
    ]
